FROM python:3.6-slim-stretch

MAINTAINER BK Lim "bklim@interviewer.ai"

RUN apt-get -y update
RUN apt-get install -y build-essential \
    python3-dev \
    python3-pip \
    python3-setuptools \
    python3-wheel \
    python3-cffi \
    libcairo2 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libgdk-pixbuf2.0-0 \
    libffi-dev \
    shared-mime-info \
    git

RUN pip install WeasyPrint==47